package:
  name: pylint
  version: "1.4.3"

source:
  fn: pylint-1.4.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint/pylint-1.4.3.tar.gz
  md5: 5924c1c7ca5ca23647812f5971d0ea44
  patches:
   # List any patch files here
   - patches/abstract_class_instantiated_py3.py.patch
   - patches/abstract_method_py3.py.patch
   - patches/class_members_py30.py.patch
   - patches/func_3k_removed_stuff_py_30.py.patch
   - patches/func_bad_exception_context_py30.py.patch
   - patches/func_continue_not_in_loop.py.patch
   - patches/func_e0108.py.patch
   - patches/func_exec_used_py30.py.patch
   - patches/func_keyword_repeat.py.patch
   - patches/func_kwoa_py30.py.patch
   - patches/func_noerror_unused_variable_py30.py.patch
   - patches/func_return_outside_func.py.patch
   - patches/func_return_yield_mix_py_33.py.patch
   - patches/func_syntax_error.py.patch
   - patches/func_undefined_metaclass_var_py30.py.patch
   - patches/func_unused_import_py30.py.patch
   - patches/func_used_before_assignment_py30.py.patch
   - patches/func_w0705.py.patch
   - patches/raising_non_exception_py3.py.patch
   - patches/syntax_error.py.patch
   - patches/unbalanced_tuple_unpacking_py30.py.patch
   - patches/undefined_variable_py30.py.patch
   - patches/unknown_encoding_py29.py.patch
   - patches/unknown_encoding_py30.py.patch
   - patches/unknown_encoding_pypy.py.patch
   - patches/yield_outside_func.py.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pylint = pylint:main
    #
    # Would create an entry point called pylint that calls pylint.main()

    - pylint = pylint:run_pylint
    - pylint-gui = pylint:run_pylint_gui
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - logilab-common >=0.53.0
    - astroid >=1.3.6
    - six

  run:
    - python
    - logilab-common >=0.53.0
    - astroid >=1.3.6
    - six

test:
  # Python imports
  imports:
    - pylint
    - pylint.checkers
    - pylint.pyreverse
    - pylint.reporters

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - pylint --help
    #- pylint-gui --help
    #- epylint --help
    - pyreverse --help
    - symilar --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pylint.org
  license: GNU General Public License (GPL)
  summary: 'python code static checker'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
