package:
  name: pylint-celery
  version: "0.3"

source:
  fn: pylint-celery-0.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint-celery/pylint-celery-0.3.tar.gz
  md5: e185f89b6af6445c0ae5a4d8b4e5e28c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pylint-celery = pylint-celery:main
    #
    # Would create an entry point called pylint-celery that calls pylint-celery.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pylint >=1.0
    - astroid >=1.0
    - pylint-plugin-utils >=0.2.1

  run:
    - python
    - pylint >=1.0
    - astroid >=1.0
    - pylint-plugin-utils >=0.2.1

test:
  # Python imports
  imports:
    - pylint_celery

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/landscapeio/pylint-celery
  license: GPLv2
  summary: 'pylint-celery is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Celery library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
