package:
  name: requirements-detector
  version: "0.4"

source:
  fn: requirements-detector-0.4.tar.gz
  url: https://pypi.python.org/packages/source/r/requirements-detector/requirements-detector-0.4.tar.gz
  md5: 6f76914e2944d070ee0e44dd75571c99
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - requirements-detector = requirements-detector:main
    #
    # Would create an entry point called requirements-detector that calls requirements-detector.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - astroid >=1.0.0

  run:
    - python
    - astroid >=1.0.0

test:
  # Python imports
  imports:
    - requirements_detector

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/landscapeio/requirements-detector
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Python tool to find and list requirements of a Python project'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
