package:
  name: setoptconf
  version: "0.2.0"

source:
  fn: setoptconf-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/s/setoptconf/setoptconf-0.2.0.tar.gz
  md5: 3ce56730d8ff700af85bda35963ab7fa
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - setoptconf = setoptconf:main
    #
    # Would create an entry point called setoptconf that calls setoptconf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - setoptconf
    - setoptconf.source

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jayclassless/setoptconf
  license: MIT License
  summary: 'A module for retrieving program settings from various sources in a consistant method.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
