package:
  name: pylint-django
  version: "0.6"

source:
  fn: pylint-django-0.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pylint-django/pylint-django-0.6.tar.gz
  md5: 4eace40f983889d2586f185a1abf1d93
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pylint-django = pylint-django:main
    #
    # Would create an entry point called pylint-django that calls pylint-django.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pylint-plugin-utils >=0.2.1
    - pylint >=1.0
    - astroid >=1.0
    - logilab-common >=0.60.0

  run:
    - python
    - pylint-plugin-utils >=0.2.1
    - pylint >=1.0
    - astroid >=1.0
    - logilab-common >=0.60.0

test:
  # Python imports
  imports:
    - pylint_django
    - pylint_django.augmentations
    - pylint_django.checkers
    - pylint_django.transforms

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/landscapeio/pylint-django
  license: GPLv2
  summary: 'pylint-django is a Pylint plugin to aid Pylint in recognising and understandingerrors caused when using the Django framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
